# Generated by Django 2.2.22 on 2022-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinjaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='comment',
            field=models.CharField(default='not available', max_length=40),
        ),
    ]
