# Generated by Django 2.2.22 on 2022-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jinjaapp', '0002_firstmodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmodel',
            name='stu_mail',
            field=models.EmailField(default='not available', max_length=60),
        ),
        migrations.AlterField(
            model_name='firstmodel',
            name='stu_name',
            field=models.CharField(default='not available', max_length=30),
        ),
        migrations.AlterField(
            model_name='firstmodel',
            name='stu_pass',
            field=models.CharField(default='not available', max_length=30),
        ),
    ]
