# Generated by Django 3.2.16 on 2022-12-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=3)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
